### ISSUE TITLE
Webpage has issues with functionality

### ISSUE THREAD

**Issue by mrzone64** [root-gg/plik#243] opened 2018-03-08 14:05 UTC
I am no words an expert or coder of any kind but in the JS console there seems to be an issue with the software mentioning some "vendor.js"
cant seem to make the "Add files" button to work either.

See for yourself here: http://134.90.151.114:8080/#/

I dont know what i did wrong, just followed the steps on the install readme. Would be great if there are any dependencies that you also list that in the readme.

Running on Ubuntu 16.04, tied on Mint 18 too, does not work on either.

**Comment by camathieu** [comment] 2018-03-08 17:19
Hello,

I think this is a duplicate of the following issue.

I still have to fix the release package, sorry for the delay.

https://github.com/root-gg/plik/issues/240

**Closed** 2018-04-11 08:41 UTC
