### ISSUE TITLE
Cannot Get Reverse proxy to work in NGINX

### ISSUE THREAD

**Issue by ekianjo** [root-gg/plik#210] opened 2017-07-20 12:45 UTC
Hi, somehow I can't get the reverse proxy function to work in NGINX with plik. 
Here is my config:

```
upstream plik { 
server 127.0.0.1:8090;   
}

server {

#I am omitting here the other parts of the config for http and https (which is working fine for other web apps anyway)

location /plik {
proxy_pass http://plik;                                    
proxy_set_header Host $host;    
proxy_set_header Connection "upgrade";
proxy_buffering off;
proxy_request_buffering off;                                          
proxy_http_version 1.1; 
proxy_buffer_size 1M; 
proxy_buffers 8 1M;
proxy_redirect off;
client_body_buffer_size 1M; 
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
}
```

I get a 404 error, and nginx says the following in the log

SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream

Any idea what is wrong? Note that while I am using https usually, i have no issue doing reverse proxy with other apps. But somehow I cannot figure what is wrong here. Any hint appreciated!

**Comment by camathieu** [comment] 2017-07-21 08:40
```
server {
        listen 443;
        server_name plik.mytld;

        ssl on;
        ssl_certificate /etc/ssl/cert.pem;
        ssl_certificate_key     /etc/ssl/key.pem;

        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;

        ssl_dhparam /etc/ssl/dhparam.pem;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
        ssl_prefer_server_ciphers on;

        add_header Strict-Transport-Security max-age=15768000;


        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_buffer_size 1M;
        proxy_buffers 8 1M;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;

        sendfile    on;
        tcp_nopush  on;
        tcp_nodelay on;

        location / {
                proxy_pass http://127.0.0.1:8080;
        }

        client_max_body_size 10G;
}

server {
        listen 80;
        server_name plik.mytld;
        return 301 https://plik.mytld$request_uri;
}
```

```
root@host:~# nginx -v
nginx version: nginx/1.6.2
root@host:~# openssl version
OpenSSL 1.0.1t  3 May 2016
root@host:~# plikd -version
Plik server v1.2 (built from git rev d44bb58 [mint,release] at 2016-12-23 15:48:40 +0100 CET with go1.7.4 linux/amd64)
```

```
root@host:~# cat /home/plik/plikd.cfg
#####
##
#  Plik - Configuration File
#

#
# Global params
#

LogLevel            = "INFO"        # Other levels : DEBUG, WARNING, CRITICAL, FATAL
ListenPort          = 8080
ListenAddress       = "127.0.0.1"
MaxFileSize         = 10737418240    # 1GB

DefaultTTL          = 2592000       # 30 days
MaxTTL              = 2592000       # 30 days

SslEnabled          = false
SslCert             = ""            # Path to your certificate file
SslKey              = ""            # Path to your certificate private key file
DownloadDomain      = "https://plik.root.gg"

YubikeyEnabled      = false         # Enable Yubikey Functionnality
YubikeyAPIKey       = ""            # Yubikey API Key (get one on https://upgrade.yubico.com/getapikey/)
YubikeyAPISecret    = ""            # Yubikey API Token

SourceIpHeader      = "X-Forwarded-For"            # If behind reverse proxy (expl: X-FORWARDED-FOR)
UploadWhitelist     = []            # Restrict upload to one or more ip range

Authentication      = false          # Enable authentication

#
# Backend choices
#

MetadataBackend     = "bolt"        # Available : file, mongo
DataBackend         = "file"        # Available : file, swift, weedfs
ShortenBackend      = ""            # Available : is.gd, w000t.me
StreamMode          = true          # Enable stream mode

#
# Backends configuration
#

[DataBackendConfig]
Directory = "/data"

[MetadataBackendConfig]
Path = "/home/plik/plik.db"

[ShortenBackendConfig]

```

**Comment by camathieu** [comment] 2017-07-21 08:52
As you only use SSL to connect to nginx ( proxy_pass http://plik; ) this looks like a problem between your client and your nginx server. This most likely has something to do with your cipher suite as I can see the error mention SSLv3. What client are you using to do the request ?

Golang disable SSLv3 by default since Go 1.5 but as you connect to the plikd server using plain HTTP this is out of scope.
https://github.com/golang/go/commit/604fa4d5a149c334ff0bd5d191c4c4e29f75545d

**Comment by ekianjo** [comment] 2017-07-21 13:05
SSL may be one problem, but actually the real issue is that plik does not accept other locations than / for the server. This is coming form server/public/js/app.js, line 129

`` var api = {base: ''};``

**Comment by camathieu** [comment] 2017-07-21 14:15
Oh I forgot the 404 part sorry. Good catch thanks, this does not looks too hard to fix.

**Comment by ekianjo** [comment] 2017-07-21 14:28
Merci CA! Let me know if you need me to test something once you make changes.

**Comment by camathieu** [comment] 2017-09-02 20:32
duplicate of https://github.com/root-gg/plik/issues/203

**Comment by camathieu** [comment] 2017-10-08 15:40
Merged in https://github.com/root-gg/plik/pull/214

**Closed** 2017-10-08 15:39 UTC
Labels: enhancement
