### ISSUE TITLE
not deleting files on filesystem

### ISSUE THREAD

**Issue by f31n** [root-gg/plik#353] opened 2021-03-28 10:28 UTC
Hey there,

does that happen just for me or does someone else have the same issue? uploaded files won't delete from the filesystem.

to reproduce: add an upload, set the config to delete after first download or only there for some days or delete it manually after uploaded, the file will no longer be access able through the user interface, but when you look into the files folder of plik (/home/plik/server/files) there is still the content.

can someone reproduce that behaviour or is my config just faulty?

**Comment by envoyfwd** [comment] 2021-04-05 10:37
Same problem, even wait a day to delete it, the file still existing in plik files, but the download link will be invalid.
There is another problem. If you set MaxTTL to -1, it will cause the program to fail to run.

**Comment by camathieu** [comment] 2021-04-12 12:21
There might be an issue with the delete logic it's the second issue on that topic.
I'll try to take a look.

**Comment by speed47** [comment] 2021-07-21 18:39
Duplicate of #352 (more over there)

**Closed** 2021-11-22 16:21 UTC
Labels: bug
